ENV['GOOGLE_CLIENT_ID'] = '364140549557-006pn8dtjcrgvo34m5afddqqjo54clnb.apps.googleusercontent.com'
ENV['GOOGLE_CLIENT_SECRET'] = 'HsSvOCTBySvUcDkeT-Tt2nFC'
ENV['PASSWORD'] = 'fbckpfnitsuhhfdl'
ENV['SENDGRID_USERNAME'] = 'arthur.roth.07@gmail.com'
ENV['SENDGRID_PASSWORD'] = 'bluea88$Peelord69'