ENV['GOOGLE_CLIENT_ID'] = '364140549557-006pn8dtjcrgvo34m5afddqqjo54clnb.apps.googleusercontent.com'
ENV['GOOGLE_CLIENT_SECRET'] = 'HsSvOCTBySvUcDkeT-Tt2nFC'
ENV['PASSWORD'] = 'fbckpfnitsuhhfdl'
ENV['SENDGRID_USERNAME'] = 'apikey'
ENV['SENDGRID_PASSWORD'] = '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'
